import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[font]
size = 12

# [font.bold]
# family = "JetBrains Mono Nerd Font Bold"
# style = "Bold"

# [font.bold_italic]
# family = "JetBrains Mono Nerd Font Bold Italic"
# style = "Bold Italic"

# [font.italic]
# family = "JetBrains Mono Nerd Font Italic"
# style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
opacity = 0.98
