require("user.plugins")
require("user.functions")
require("user.plugins")
require("user.which_key")
require("user.lualine")
require("user.os_specific")
require("user.treesitter")
require("user.general")
require("user.keymaps")
require("user.formatters")
require("user.linters")
require("user.autocommands")
require("user.lsp")
require("user.python")

-- TODO: use async capability so that it doesn't effect start-up time
-- require("user.git")
