[pyprland]
plugins = [
  "scratchpads",
  "lost_windows",
  "monitors",
  "shift_monitors",
  "toggle_dpms",
  "magnify",
  "expose",
  "shift_monitors",
  "workspaces_follow_focus",
  "layout_center"
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

[scratchpads.stb]
animation = "fromBottom"
command = "kitty --class kitty-stb sstb"
class = "kitty-stb"
lazy = true
size = "75% 45%"

[scratchpads.stb-logs]
animation = "fromTop"
command = "kitty --class kitty-stb-logs stbLog"
class = "kitty-stb-logs"
lazy = true
size = "75% 40%"

[scratchpads.term2]
animation = "fromTop"
command = "kitty --class kitty-dropterm2"
class = "kitty-dropterm2"
size = "75% 60%"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "pavucontrol"
size = "40% 90%"
unfocus = "hide"
lazy = true

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
unfocus = "hide"
size = "75% 60%"

[scratchpads.music]
animation = "fromTop"
command = "kitty --class music -e ytermusic-proxy"
class = "music"
size = "75% 60%"

[scratchpads.file]
animation = "fromTop"
command = "kitty --class yazi -e yazi ~/mhome"
class = "yazi"
size = "75% 60%"

[scratchpads.elia]
animation = "fromLeft"
command = "kitty --class elia -e elia-proxy"
class = "elia"
size = "85% 75%"

[scratchpads.top]
animation = "fromTop"
command = "kitty --class btop -e btop"
class = "htop"
lazy= true
size = "75% 60%"

[monitors]
unknown = "wlrlui"

[monitors.placement]
"Ancor".leftOf = ["LG"]
#<D-a> "Sony".topOf = ["Brand X"]

[layout_center]
margin = 60
offset = [0, 30]
next = "movefocus l"
prev = "movefocus h"
