for _, plugin in ipairs({
	"nvim-treesitter-objects",
	"vista",
	"vim-surround",
	"vim-signature",
	"vim-sanegx",
	"vim-jsx-pretty",
	"vim-javascript",
	"undotree",
	"trouble",
	"todo-comments",
  "tint",
  "eyeliner",
	"dadbod",
	"ssr",
	"nvim-treesitter-objects",
	-- "cord",
	"bookmarks",
	-- "nvim-colorizer",
	"figlet",
	"leap",
	"noice",
	-- "no-neck-pain",
	"nvim-highlight-colors",
	"easytables",
	"icon-picker",
	"gruvbox",
	"goto-preview",
	"in_and_out",
	"glow",
	"dressing",
	-- "clever-f",
	"ChatGPT.ChatGPT",
	"nvim-nio",
  "kanagawa",
}) do
	lvim.plugins[#lvim.plugins + 1] = require("user.plugins_dir." .. plugin)
end
