for _, plugin in ipairs({
  "nvim-treesitter-objects",
  "vista",
  "vim-surround",
  "vim-signature",
  "vim-sanegx",
  "vim-notify",
  "vim-jsx-pretty",
  "vim-javascript",
  "undotree",
  "trouble",
  "todo-comments",
  "ssr",
  "nvim-treesitter-objects",
  "nvim-colorizer",
  "noice",
  "no-neck-pain",
  "gruvbox",
  "goto-preview",
  "glow",
  "dressing",
  "clever-f",
  "ChatGPT",
  "tint",
  "kanagawa",
}) do
  lvim.plugins[#lvim.plugins + 1] = require("user.plugins_dir." .. plugin)
end
